version: '3'
services:
  db:
    container_name: db
    image: postgres:latest
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
        #- ./schemas.sql:/docker-entrypoint-initdb.d/schemas.sql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

volumes:
    db-data:
