version: '3'
services:
  db:
    container_name: db
    image: postgres:alpine
    restart: always
    volumes:
      - /srv/DownloadsAndSoftware/EIP/db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

volumes:
    db-data:
